### ISSUE TITLE
Failed to load model object file

### ISSUE THREAD

**Issue by t0maszduda** [antic-ml/javidx9#1]
I have "Failed to load model object file"
and black screen 
path for obj files: boolean loaded = ship.loadFromObjectFile("obj/ship.obj");

and I tryed put everywhere and the same
and try put own flle obj from Blender and also teapot.obj

Thanks

**Comment by antic-ml** [comment]
Try this instead:

`boolean loaded = ship.loadFromObjectFile("/obj/ship.obj");`

I think you were missing a '/' character in the path.

**Comment by t0maszduda** [comment]
Hi

Thanks for reply

unfortunetly I have: boolean loaded = ship.loadFromObjectFile("/obj/ship.obj”);

and still problem 
:(
 What do You think?

**Comment by antic-ml** [comment]
Hi

I just checked the code and it needs the full absolute path to the obj file. On my machine, I do this:

`boolean loaded = ship.loadFromObjectFile("c:/users/mario/javidx93d/obj/ship.obj”);`

Try again with the full absolute path to your .obj file.

--Mario

**Comment by antic-ml** [comment]
No I was wrong. That is not going to work. The correct statement to have in your code is as follows:
`boolean loaded = ship.loadFromObjectFile("/obj/ship.obj”);`

Ensure that the obj directory containing the object files is in the correct place. Your directory structure should look like this:

`javdix93D/
obj/`

The javidx93D directory contains the compiled class files and the obj directory contains the model files.

--Mario

**Comment by t0maszduda** [comment]
hmm

still doesn't work :(

Tom

**Comment by antic-ml** [comment]
What OS are you using and what is the command you are using to launch the Java program?

**Comment by t0maszduda** [comment]
I have mac and IntelliJ and  there are nothing „red” and everything compile except obj..

**Comment by antic-ml** [comment]
I'm using IntgelliJ too on a Windows machine and it works fine. Do you have the working directory in the Run Configuration setup correctly? Open the Run->Run... menu in IntelliJ in the Run window check that the working directory points to the directory containing your IntelliJ project. For example on my machine, the working directory is set to:
`C:\Users\Mario Gianota\javidx9`

Which is where I have the project.

**Comment by antic-ml** [comment]
Also, ensure that the obj directory containing the .obj files have been copied to the project's out/production directory, otherwise the program won't be able to find them.

**Comment by t0maszduda** [comment]
here is no second  folder obj as in Windows

**Comment by antic-ml** [comment]
Put the obj folder in the out/production folder and rerun the application. It should then work.

**Comment by t0maszduda** [comment]
I don’t have on this project out folder instedof I have target

**Comment by antic-ml** [comment]
Okay. Are the compiled class files in your target folder? 

The reason it is not working for you is that the obj folder must be in the same folder as the the one the javidx9 folder containing the class files is in.

**Comment by t0maszduda** [comment]
YES!!!!!!

it works!!!!

I had to create obj folder and  copied obj file  to target folder and works!!!!

Is it possible that app will be create that file automatically?

**Comment by antic-ml** [comment]
I though it would work if you copied the files 👍 

The app won't copy the files automatically, you have to do it yourself. It is not a very sophisticated app.

**Comment by t0maszduda** [comment]
Hi 
Do You have time and would you like to help me with my project?

**Comment by antic-ml** [comment]
Depends how large your project is and what it is about. If it is only small and something I can do then I can probably help out.

**Comment by t0maszduda** [comment]
this is my email tomasz.duda@post.pl could you write on it as contact for future thanks
